### ISSUE TITLE
asset_url helpers don't work

### ISSUE THREAD

**Issue by ssalzberg** [rails/dartsass-rails#18]
In switching over from sass-rails to dartsass-rails, I noticed the asset path helpers no longer work. In development mode, something like this works fine:

```
div {
    background-image: url("path/in/assets/to/image.jpg");
}
```

but in production, neither that nor this works:

```
div {
    background-image: asset-url("path/in/assets/to/image.jpg");
}
```

**Comment by ntkme** [comment]
`dartsass-rails` cannot pass ruby functions to the dart sass compiler, so that it does not support asset helpers.

If you need the `asset-url` helper, you can try [sassc-embedded](https://github.com/ntkme/sassc-embedded-shim-ruby). It is based on `dart-sass-embedded` and provides a ruby API that is compatible with SassC so that sprockets would work as is.

**Comment by dhh** [comment]
Latest Sprockets and Propshaft will both replace url() to an digest-stamped version.
